package com.assignment;

public class TestException {

	public static void main(String[] args) {

		
		
		try
		{
			int a = 10/0;
		}
		catch(ArithmeticException e)
		{
			System.out.println("ArithmeticException occured: "+e.getMessage());
		}
	}

}
